router:
  build: tests/.
  ports:
    - "8080:8080"

test:
  build: .
  links:
    - router
  volumes:
    - "/home/ubuntu/python-crossbarhttp:/home/ubuntu/python-crossbarhttp"
  environment:
    ROUTER_URL: http://router:8080
